### ISSUE TITLE
Broken link in `integrating-with-library.md`

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-lib#107]
Hello, 

In the introduction in [this document](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/main/integrating-with-library.md) there is a broken link to the example `AuthAwareTokenConverter.kt` file.

It's pointing to https://github.com/ministryofjustice/hmpps-digital-prison-reporting-mi/blob/main/src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/AuthAwareTokenConverter.kt#L15 but this file doesn't exist anymore :)

**Comment by gavriil-g-moj** [comment]
Created the following ticket to address this:
https://dsdmoj.atlassian.net/browse/DPR2-492

**Comment by gavriil-g-moj** [comment]
This has now been fixed.

**Comment by xoen** [comment]
Awesome, thank you @gavriil-g-moj ☺️
