### ISSUE TITLE
`Failed to load ApplicationContext` error when trying to integrate

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-lib#108]
Hello,

I'm playing with the integration of this in the Non-associations API but I'm getting some weird errors, both [in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-non-associations-api/1104/workflows/cbe7dd18-8651-40c2-8031-94d56e5f677b/jobs/3855/tests) and when running tests locally: 

```
java.lang.IllegalStateException: ApplicationContext failure threshold (1) exceeded: skipping repeated attempt to load context for [MergedContextConfiguration@373754a testClass = uk.gov.justice.digital.hmpps.hmppsnonassociationsapi.jpa.repository.NonAssociationsRepositoryTest, locations = [], classes = [uk.gov.justice.digital.hmpps.hmppsnonassociationsapi.HmppsNonAssociationsApi], contextInitializerClasses = [], activeProfiles = ["test"], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.autoconfigure.OverrideAutoConfigurationContextCustomizerFactory$DisableAutoConfigurationContextCustomizer@590b7982, org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.filter.TypeExcludeFiltersContextCustomizer@34be3d80, 

[...]
```

I'm trying to follow [the integration documentation](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/main/integrating-with-library.md) but admittedly my SpringBoot is not the best so I'm sure I'm missing something obvious.

You can see the project and [what I've done in this branch here](https://github.com/ministryofjustice/hmpps-non-associations-api/compare/NON-347--reporting-lib?expand=1) - I've also had a look at [a similar PR](https://github.com/ministryofjustice/hmpps-prisoner-communication-monitoring-api/pull/504/files) but I don't see much of a difference to explain this.

The application seems to start fine and I can see the new reporting endpoint in the Swagger docs - which is encouraging - but tests fail.

**Comment by Mjwillis** [comment]
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/119 blocks this issue

**Comment by xoen** [comment]
**UPDATE**: FYI: Tests now run both locally and in CI and I've successfully deployed the API changes to `dev`.
[I'm seeing the DPR endpoints in the swagger docs here](https://non-associations-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/), so that's very promise and I think I can close this specific issue now ☺️ 

I'm making some tweaks to the UI side of the changes and I'll update the other issue after I've done that and UI part is also in `dev` ☺️ (but it seems like the auto-configuration change works now!)
